### ISSUE TITLE
[AppUpdate] 'Not found' error appears after updating app and opening MyAccount

### ISSUE THREAD

**Issue by haliakhnovich** [LaV0n/my-anime#17]
'Not found' error appears after updating app and opening MyAccount.
Seems like actual adter opening any page, not only MyAccount.

![Image](https://github.com/LaV0n/my-anime/assets/1487530/7c6a9135-bfd5-4ffb-8a56-f79c44c2a072)

**Comment by LaV0n** [comment]
fixed
