### ISSUE TITLE
[Search][Seasonal][MyList] Search by EN title doesn't work

### ISSUE THREAD

**Issue by haliakhnovich** [LaV0n/my-anime#20]
Search by EN title doesn't work 
e.g. Okashi na Tensei (Sweet Reincarnation) 

![Image](https://github.com/LaV0n/my-anime/assets/1487530/af300ff6-62ca-436a-b6cc-2b7ad1336818)
![Image](https://github.com/LaV0n/my-anime/assets/1487530/5b65b5de-1d7f-43e6-bb81-9359ebf4d915)

**Comment by LaV0n** [comment]
fixed search in my list
