### ISSUE TITLE
[Search][Seasonal][MyList] Use en title in the search list if it exists

### ISSUE THREAD

**Issue by haliakhnovich** [LaV0n/my-anime#8]
- [x] Use enlish title in the serach list if it exists, otherwise show default title

**Comment by LaV0n** [comment]
added eng title priority

**Comment by haliakhnovich** [comment]
Reopened. Doesn't work.
e.g. Okashi na Tensei (Sweet Reincarnation) from Last season

![Image](https://github.com/LaV0n/my-anime/assets/1487530/eee2fe06-dcee-410e-9b53-c311ef053d1e)
![Image](https://github.com/LaV0n/my-anime/assets/1487530/7ffa6e22-6389-4bab-b7ae-dc5bbc16fa81)
![Image](https://github.com/LaV0n/my-anime/assets/1487530/eb46e150-a900-4b3a-adfa-191925bedcb3)

**Comment by LaV0n** [comment]
fixed main title name
